### ISSUE TITLE
好像启动时的自动刷新版本报错了

### ISSUE THREAD

**Issue by Sylphinford** [SonderXiaoming/pcrjjc_huannai2#11]
海外网络，所以不是网络问题
bot启动完后，开始JJC任务就报错。然后整个bot停止了。。gohttp直接连不上bot。。

如何跳过版本检测

```
[2024-02-23 23:08:35,313 nonebot] INFO: Scheduler started
done
[2024-02-23 23:08:35,485 nonebot] INFO: 加载账号：ID, 服务器：渠
[2024-02-23 23:08:35,516 nonebot] INFO: 加载账号：ID, 服务器：B服
[2024-02-23 23:08:36,173 nonebot] INFO: 失败： 未能完成查询请求。
[2024-02-23 23:08:36,204 nonebot] INFO: Traceback (most recent call last):
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 228, in __call__
    await self.app.startup()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2149, in startup
    await func()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\__init__.py", line 486, in on_arena_schedule
    await login_all()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\query.py", line 121, in login_all
    client = tw_pcrclient(i.account, i.password, i.viewer_id, tw_platform)
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 74, in __init__
    self.headers = get_headers().copy()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 19, in get_headers
    app_ver = get_ver()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 56, in get_ver
    app_ver = ver_tmp.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\__init__.py", line 39, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\run.py", line 66, in worker_serve
    raise exception
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 230, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 80, in asgi_send
    raise LifespanFailure("startup", message["message"])
hypercorn.utils.LifespanFailure: Lifespan failure in startup. ''NoneType' object has no attribute 'text''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\query.py", line 24, in _query
    DA = await queue.get()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\asyncio\queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

[2024-02-23 23:08:36,206 nonebot] INFO: 失败：0 未能完成查询请求。
[2024-02-23 23:08:36,218 nonebot] INFO: Traceback (most recent call last):
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 228, in __call__
    await self.app.startup()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2149, in startup
    await func()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\__init__.py", line 486, in on_arena_schedule
    await login_all()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\query.py", line 121, in login_all
    client = tw_pcrclient(i.account, i.password, i.viewer_id, tw_platform)
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 74, in __init__
    self.headers = get_headers().copy()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 19, in get_headers
    app_ver = get_ver()
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\client\tw_pcrclient.py", line 56, in get_ver
    app_ver = ver_tmp.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\__init__.py", line 39, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\run.py", line 66, in worker_serve
    raise exception
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 230, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 80, in asgi_send
    raise LifespanFailure("startup", message["message"])
hypercorn.utils.LifespanFailure: Lifespan failure in startup. ''NoneType' object has no attribute 'text''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\pcrjjc_huannai2\query.py", line 24, in _query
    DA = await queue.get()
  File "C:\Users\nekomimi\AppData\Local\Programs\Python\Python38\lib\asyncio\queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError
```

**Comment by SonderXiaoming** [comment]
更新一下

**Comment by Sylphinford** [comment]
能行了。谢谢
