### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by XingseLiuli** [SonderXiaoming/pcrjjc_huannai2#2]
ERROR: Failed to import "hoshino.modules.pcrjjc_huannai2.query", error: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
[2023-07-08 19:25:11,721 nonebot] ERROR: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
Traceback (most recent call last):

**Comment by SonderXiaoming** [comment]
需要更多报错信息

**Comment by XingseLiuli** [comment]
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
[2023-07-10 15:30:19,085 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc_huannai2.query", error: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
[2023-07-10 15:30:19,085 nonebot] ERROR: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

 File "C:\Users\Administrator\Desktop\公主连结bot\整合包v2.0\整合包v2.0\krayu\HoshinoBot\hoshino\modules\pcrjjc_huannai2\__init__.py", line 15, in <module>
    from .tool import refresh_account
  File "C:\Users\Administrator\Desktop\公主连结bot\整合包v2.0\整合包v2.0\krayu\HoshinoBot\hoshino\modules\pcrjjc_huannai2\tool.py", line 9, in <module>
    acinfo: list = load(fp)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
[2023-07-10 15:30:19,186 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc_huannai2.tool", error: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
[2023-07-10 15:30:19,186 nonebot] ERROR: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\公主连结bot\整合包v2.0\整合包v2.0\krayu\HoshinoBot\hoshino\modules\pcrjjc_huannai2\__init__.py", line 15, in <module>
    from .tool import refresh_account
  File "C:\Users\Administrator\Desktop\公主连结bot\整合包v2.0\整合包v2.0\krayu\HoshinoBot\hoshino\modules\pcrjjc_huannai2\tool.py", line 9, in <module>
    acinfo: list = load(fp)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb7 in position 246: illegal multibyte sequence

**Comment by XingseLiuli** [comment]
不是很懂编程，只能把报错的地方都给粘贴过来了φ(゜▽゜*)♪

**Comment by SonderXiaoming** [comment]
更新一下试试

**Comment by XingseLiuli** [comment]
还是有报错
[2023-07-16 16:32:17,341 hoshino] WARNING: Failed to add prefix trigger `竞技场帮助`: Conflicts between send_jjchelp and wrapper
[2023-07-16 16:32:17,341 hoshino] WARNING: Failed to add prefix trigger `查询竞技场订阅数`: Conflicts between pcrjjc_number and wrapper
[2023-07-16 16:32:17,378 hoshino] WARNING: Failed to add prefix trigger `竞技场订阅状态`: Conflicts between send_arena_sub_status and wrapper
[2023-07-16 16:32:17,378 nonebot] ERROR: Failed to import "hoshino.modules.pcrjjc_huannai2.query", error: on_prefix() takes from 2 to 3 positional arguments but 4 were given
[2023-07-16 16:32:17,378 nonebot] ERROR: on_prefix() takes from 2 to 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\公主连结bot\整合包v2.0\整合包v2.0\krayu\HoshinoBot\hoshino\modules\pcrjjc_huannai2\__init__.py", line 436, in <module>
    @sv_b.on_prefix('竞技场换头像框', '更换竞技场头像框', '更换头像框')
TypeError: on_prefix() takes from 2 to 3 positional arguments but 4 were given

**Comment by SonderXiaoming** [comment]
更新hoshino
