### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by zhtyirg3** [SonderXiaoming/pcrjjc_huannai2#9]
查询竞技场报错，不知道是什么问题，大佬看看怎么解决，应该该安装的都安装了。
![2263951414](https://github.com/SonderXiaoming/pcrjjc_huannai2/assets/55908974/e928b155-eae3-4ae5-b270-0f274ff718b0)

**Comment by SonderXiaoming** [comment]
好像是文件损坏，你先删了重装试试

**Comment by zhtyirg3** [comment]
> 好像是文件损坏，你先删了重装试试

![3086613157](https://github.com/SonderXiaoming/pcrjjc_huannai2/assets/55908974/cd4203a5-3611-44fc-9b92-6f3f29a78a24)

**Comment by zhtyirg3** [comment]
> 好像是文件损坏，你先删了重装试试

[2023-09-24 01:33:04,079 nonebot] INFO： 竞技场推送开始
Traceback (most recent call last):
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/perclient.py", line 122, in callapi
response = perclient.unpack(
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/perclient.py", line 106, in unpack
data = b64decode (data.decode ('utf8' ))
File "/us/local/lib/python3.8/base64.py", line 87, in b64decode return binascii.a2b_base64 (s) binascii.Error: Incorrect padding
[2023-09-24 01:33:04,507 nonebot〕 INFO: xxx1234@126.com查 询 1081267482767失败
[2023-09-24 01:33:04,507 nonebot] INFO: Traceback (most recent call last):
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/pcrclient.py", line 122, in callapi
response = perclient. unpack(
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/perclient.py", line 106, in unpack
data = b64decode (data.decode ('utf8' ))
File "/usr/local/lib/python3.8/base64py", line 87, in b64decode return binascii.a2b_base64 (s) binascii.Error: Incorrect padding
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/query.py", line 31, in _query await client. login()
＃失败重连
File "/root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/pcrclient.py",line 189, in login await self.callapi ('/check/check_agreement', {})
File "/ root/bot/HoshinoBot/hoshino/modules/pcrjjc_huannai2/client/perclient.py", line 144, in callapi
raise ApiException("未知错误" + str(e)，501）
hoshino. modules. pcrjjc_huannai2.client pcrclient .ApiException：未知错误Incorrect padding

重新安排了，还是不行，连绑定都绑定不上

**Comment by SonderXiaoming** [comment]
Incorrect padding是类似网络异常，你多试几次

**Comment by zhtyirg3** [comment]
> Incorrect padding是类似网络异常，你多试几次

我的是海外服务器，这个是有关系的么，我试试

**Comment by zhtyirg3** [comment]
> Incorrect padding是类似网络异常，你多试几次

![869025004](https://github.com/SonderXiaoming/pcrjjc_huannai2/assets/55908974/cd7c0755-3925-46ce-87f5-19dc88be862d)
不行，绑定了，查询报错，用公版没问题

**Comment by SonderXiaoming** [comment]
sqlalchemy版本，aiosqlite版本，sqlmodel版本给我栞栞

**Comment by zhtyirg3** [comment]
> sqlalchemy版本，aiosqlite版本，sqlmodel版本

root@snappy-bits-2:~# pip install sqlalchemy
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.8/site-packages (1.4.41)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/site-packages (from sqlalchemy) (2.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@snappy-bits-2:~# pip install aiosqlite
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.8/site-packages (0.19.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@snappy-bits-2:~# pip install sqlmodel
Requirement already satisfied: sqlmodel in /usr/local/lib/python3.8/site-packages (0.0.8)
Requirement already satisfied: SQLAlchemy<=1.4.41,>=1.4.17 in /usr/local/lib/python3.8/site-packages (from sqlmodel) (1.4.41)
Requirement already satisfied: pydantic<2.0.0,>=1.8.2 in /usr/local/lib/python3.8/site-packages (from sqlmodel) (1.10.12)
Requirement already satisfied: sqlalchemy2-stubs in /usr/local/lib/python3.8/site-packages (from sqlmodel) (0.0.2a35)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.8/site-packages (from pydantic<2.0.0,>=1.8.2->sqlmodel) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/site-packages (from SQLAlchemy<=1.4.41,>=1.4.17->sqlmodel) (2.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

重新安装了一次

**Comment by zhtyirg3** [comment]
> sqlalchemy版本，aiosqlite版本，sqlmodel版本给我栞栞

版本如上，是否是海外服务器的原因？

**Comment by SonderXiaoming** [comment]
你可以本地试试先，然后尝试降级aiosqlite到0.17版本
